using System.Text.Json;
using System.Text.Json.Serialization;
using PZMapForge.Core.ParsedCell;
using PZMapForge.Core.Regions;
using Xunit;

namespace PZMapForge.Core.Tests.Regions;

/// <summary>
/// Cross-verification: asserts that the .NET RegionExtractor produces results
/// that match the PowerShell extract-regions.ps1 reference output.
///
/// Both sides read from tests/fixtures/parsed-cell/valid.json (the same input).
/// The PS reference output is committed at tests/fixtures/regions/valid.json
/// (generated by running extract-regions.ps1 against that fixture).
///
/// Claim boundary: planning artifact only. No PZ export claim.
/// </summary>
public sealed class RegionCrossVerificationTests
{
    // -----------------------------------------------------------------------
    // Paths
    // -----------------------------------------------------------------------

    private static string RepoRoot =>
        Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));

    private static string ParsedCellFixture =>
        Path.Combine(RepoRoot, "tests", "fixtures", "parsed-cell", "valid.json");

    private static string RegionsFixture =>
        Path.Combine(RepoRoot, "tests", "fixtures", "regions", "valid.json");

    // -----------------------------------------------------------------------
    // Helpers: load .NET extraction result
    // -----------------------------------------------------------------------

    private static RegionExtractionResult ExtractFromFixture()
    {
        var loaded = ParsedCellLoader.Load(ParsedCellFixture);
        Assert.True(loaded.IsValid, string.Join("; ", loaded.Errors));

        var codeToKind = loaded.Document!.Counts
            .ToDictionary(c => c.Code[0], c => c.Kind)
            .AsReadOnly();

        return RegionExtractor.Extract(loaded.Grid!, codeToKind);
    }

    // -----------------------------------------------------------------------
    // Helpers: load PS reference from committed fixture
    // -----------------------------------------------------------------------

    private static PsRegionsDoc LoadPsFixture()
    {
        var json = File.ReadAllText(RegionsFixture);
        return JsonSerializer.Deserialize<PsRegionsDoc>(json, JsonOptions)
               ?? throw new InvalidOperationException("Failed to deserialize PS regions fixture.");
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        AllowTrailingCommas         = true,
        PropertyNameCaseInsensitive = false,
    };

    // -----------------------------------------------------------------------
    // Test 1: total region count and pixel count match
    // -----------------------------------------------------------------------

    [Fact]
    public void CrossVerify_TotalsMatch()
    {
        var dotnet = ExtractFromFixture();
        var ps     = LoadPsFixture();

        Assert.Equal(ps.TotalRegions, dotnet.TotalRegions);
        Assert.Equal(ps.SummaryByKind.Sum(s => s.TotalPixels), dotnet.TotalPixels);
    }

    // -----------------------------------------------------------------------
    // Test 2: summary_by_kind matches on all metrics per kind
    // -----------------------------------------------------------------------

    [Fact]
    public void CrossVerify_SummaryByKindMatches()
    {
        var dotnet    = ExtractFromFixture();
        var ps        = LoadPsFixture();
        var psLookup  = ps.SummaryByKind.ToDictionary(s => s.Kind, StringComparer.Ordinal);
        var dotLookup = dotnet.SummaryByKind.ToDictionary(s => s.Kind, StringComparer.Ordinal);

        // Every PS kind must exist in .NET summary
        foreach (var (kind, psSummary) in psLookup)
        {
            Assert.True(dotLookup.TryGetValue(kind, out var dotSummary),
                $"Kind '{kind}' present in PS fixture but missing from .NET output.");

            Assert.Equal(psSummary.RegionCount,         dotSummary!.RegionCount);
            Assert.Equal(psSummary.TotalPixels,         dotSummary.TotalPixels);
            Assert.Equal(psSummary.LargestRegionPixels, dotSummary.LargestRegionPixels);
        }

        // No extra kinds in .NET
        Assert.Equal(psLookup.Count, dotLookup.Count);
    }

    // -----------------------------------------------------------------------
    // Test 3: individual region details match (all 9, since fewer than 20)
    // -----------------------------------------------------------------------

    [Fact]
    public void CrossVerify_RegionDetailsMatch()
    {
        var dotnet    = ExtractFromFixture();
        var ps        = LoadPsFixture();
        int compareN  = Math.Min(ps.Regions.Count, Math.Min(dotnet.TotalRegions, 20));

        for (int i = 0; i < compareN; i++)
        {
            var psR  = ps.Regions[i];
            var dotR = dotnet.Regions[i];
            var lbl  = $"region[{i}] (id={psR.RegionId}, kind={psR.Kind})";

            Assert.Equal(psR.Kind,      dotR.Kind);
            Assert.Equal(psR.Code,      dotR.Code.ToString());
            Assert.Equal(psR.PixelCount, dotR.PixelCount);

            Assert.Equal(psR.Bounds.X,      dotR.Bounds.X);
            Assert.Equal(psR.Bounds.Y,      dotR.Bounds.Y);
            Assert.Equal(psR.Bounds.Width,  dotR.Bounds.Width);
            Assert.Equal(psR.Bounds.Height, dotR.Bounds.Height);

            Assert.Equal(psR.Centroid.X, dotR.Centroid.X, 2);
            Assert.Equal(psR.Centroid.Y, dotR.Centroid.Y, 2);
        }
    }

    // -----------------------------------------------------------------------
    // Minimal deserialization models for the PS regions.json fixture
    // -----------------------------------------------------------------------

    private sealed class PsRegionsDoc
    {
        [JsonPropertyName("total_regions")]
        public int TotalRegions { get; set; }

        [JsonPropertyName("regions")]
        public List<PsRegion> Regions { get; set; } = [];

        [JsonPropertyName("summary_by_kind")]
        public List<PsSummary> SummaryByKind { get; set; } = [];
    }

    private sealed class PsRegion
    {
        [JsonPropertyName("region_id")]
        public int RegionId { get; set; }

        [JsonPropertyName("kind")]
        public string Kind { get; set; } = string.Empty;

        [JsonPropertyName("code")]
        public string Code { get; set; } = string.Empty;

        [JsonPropertyName("pixel_count")]
        public int PixelCount { get; set; }

        [JsonPropertyName("bounds")]
        public PsBounds Bounds { get; set; } = new();

        [JsonPropertyName("centroid")]
        public PsCentroid Centroid { get; set; } = new();
    }

    private sealed class PsBounds
    {
        [JsonPropertyName("x")]      public int X      { get; set; }
        [JsonPropertyName("y")]      public int Y      { get; set; }
        [JsonPropertyName("width")]  public int Width  { get; set; }
        [JsonPropertyName("height")] public int Height { get; set; }
    }

    private sealed class PsCentroid
    {
        [JsonPropertyName("x")] public double X { get; set; }
        [JsonPropertyName("y")] public double Y { get; set; }
    }

    private sealed class PsSummary
    {
        [JsonPropertyName("kind")]
        public string Kind { get; set; } = string.Empty;

        [JsonPropertyName("region_count")]
        public int RegionCount { get; set; }

        [JsonPropertyName("total_pixels")]
        public int TotalPixels { get; set; }

        [JsonPropertyName("largest_region_pixels")]
        public int LargestRegionPixels { get; set; }
    }
}
