using System.Text;
using System.Text.Json;

namespace PZMapForge.Core.WorldGen;

public static class WorldGenCompiler
{
    private const string RequiredFormat = "pzmapforge.worldgen.layers.v1";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        AllowTrailingCommas     = true,
        ReadCommentHandling     = JsonCommentHandling.Skip,
        PropertyNameCaseInsensitive = false,
    };

    public static WorldGenCompileResult Compile(string inputPath)
    {
        var result = new WorldGenCompileResult();

        if (!File.Exists(inputPath))
        {
            result.Errors.Add($"Input file not found: {inputPath}");
            return result;
        }

        WorldGenManifest manifest;
        try
        {
            var json = File.ReadAllText(inputPath);
            manifest = JsonSerializer.Deserialize<WorldGenManifest>(json, JsonOptions)
                       ?? throw new JsonException("Deserialized to null.");
        }
        catch (Exception ex)
        {
            result.Errors.Add($"JSON parse error: {ex.Message}");
            return result;
        }

        Validate(manifest, result.Errors);
        if (!result.IsValid) return result;

        result.MapId       = manifest.MapId;
        result.ModuleCount = manifest.StaticModules.Count;
        result.Lua         = EmitLua(manifest);
        return result;
    }

    private static void Validate(WorldGenManifest manifest, List<string> errors)
    {
        if (string.IsNullOrWhiteSpace(manifest.MapId))
            errors.Add("map_id is missing or empty.");

        if (manifest.Format != RequiredFormat)
            errors.Add($"format must be '{RequiredFormat}', got '{manifest.Format}'.");

        if (manifest.StaticModules == null || manifest.StaticModules.Count == 0)
        {
            errors.Add("static_modules list is missing or empty.");
            return;
        }

        var seenIds = new HashSet<string>(StringComparer.Ordinal);

        for (var i = 0; i < manifest.StaticModules.Count; i++)
        {
            var mod    = manifest.StaticModules[i];
            var prefix = $"static_modules[{i}]";

            if (string.IsNullOrWhiteSpace(mod.Id))
                errors.Add($"{prefix}: id is missing or empty.");
            else if (!seenIds.Add(mod.Id))
                errors.Add($"{prefix}: duplicate id '{mod.Id}'.");

            if (mod.Type is not ("biome" or "prefab"))
                errors.Add($"{prefix} (id={mod.Id}): type must be 'biome' or 'prefab', got '{mod.Type}'.");

            if (string.IsNullOrWhiteSpace(mod.Key))
            {
                errors.Add($"{prefix} (id={mod.Id}): key is missing or empty.");
            }
            else if (mod.Type == "biome" && !WorldGenRegistry.Biomes.Contains(mod.Key))
            {
                var known = string.Join(", ", WorldGenRegistry.Biomes);
                errors.Add($"{prefix} (id={mod.Id}): unknown biome key '{mod.Key}'. Known: {known}.");
            }
            else if (mod.Type == "prefab" && !WorldGenRegistry.Prefabs.Contains(mod.Key))
            {
                var known = string.Join(", ", WorldGenRegistry.Prefabs);
                errors.Add($"{prefix} (id={mod.Id}): unknown prefab key '{mod.Key}'. Known: {known}.");
            }

            if (mod.X2 < mod.X1)
                errors.Add($"{prefix} (id={mod.Id}): x2 ({mod.X2}) must be >= x1 ({mod.X1}).");
            if (mod.Y2 < mod.Y1)
                errors.Add($"{prefix} (id={mod.Id}): y2 ({mod.Y2}) must be >= y1 ({mod.Y1}).");
        }
    }

    private static string EmitLua(WorldGenManifest manifest)
    {
        var count     = manifest.StaticModules.Count;
        var timestamp = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ");
        var sb        = new StringBuilder();

        sb.AppendLine("-- ========================================================");
        sb.AppendLine("-- Generated by PZMapForge");
        sb.AppendLine($"-- Map ID: {manifest.MapId}");
        sb.AppendLine($"-- Format: {manifest.Format}");
        sb.AppendLine($"-- Module count: {count}");
        sb.AppendLine($"-- Generated: {timestamp}");
        sb.AppendLine("-- ========================================================");
        sb.AppendLine();
        sb.AppendLine($"print(\"PZMAPFORGE_WORLDGENOVERRIDE_LOADED\")");
        sb.AppendLine($"print(\"PZMAPFORGE_WORLDGENOVERRIDE_MAP_ID={manifest.MapId}\")");
        sb.AppendLine($"print(\"PZMAPFORGE_WORLDGENOVERRIDE_MODULE_COUNT={count}\")");
        sb.AppendLine();
        sb.AppendLine("worldgen[\"static_modules\"] = {");

        for (var i = 0; i < count; i++)
        {
            var mod    = manifest.StaticModules[i];
            var isLast = i == count - 1;

            sb.AppendLine($"    -- {mod.Id}");
            sb.AppendLine("    {");
            sb.AppendLine($"        position = {{ xmin = {mod.X1}, xmax = {mod.X2}, ymin = {mod.Y1}, ymax = {mod.Y2} }},");

            if (mod.Type == "biome")
                sb.AppendLine($"        biome = worldgen.biomes.{mod.Key}");
            else
                sb.AppendLine($"        prefab = worldgen.prefabs.{mod.Key}");

            sb.AppendLine(isLast ? "    }" : "    },");

            if (!isLast)
                sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}
