using System.Text.Json;
using PZMapForge.Core.ParsedCell;
using PZMapForge.Core.Planning;
using PZMapForge.Core.Primitives;
using PZMapForge.Core.Regions;
using Xunit;

namespace PZMapForge.Core.Tests.Planning;

/// <summary>
/// Cross-verification: asserts that the .NET planning pipeline produces
/// artifacts that match the committed reference fixture.
///
/// Input: tests/fixtures/parsed-cell/valid.json (9 regions, 9 primitives).
/// Reference: tests/fixtures/plan-recommendations/valid.json
///   (generated by running the .NET writer with FixedTs = 2026-01-01T00:00:00Z).
///
/// On first run (no reference fixture), the test generates and commits the fixture.
/// On subsequent runs it verifies field-by-field (excluding generated_at_utc
/// and source.parsed_cell_path which are machine-specific).
///
/// Claim boundary: planning_artifact_only_not_pz_load_tested
/// </summary>
public sealed class PlanningArtifactCrossVerificationTests : IDisposable
{
    private readonly string _tempDir =
        Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());

    public PlanningArtifactCrossVerificationTests() =>
        Directory.CreateDirectory(_tempDir);

    public void Dispose()
    {
        if (Directory.Exists(_tempDir))
            Directory.Delete(_tempDir, recursive: true);
    }

    // -----------------------------------------------------------------------
    // Paths
    // -----------------------------------------------------------------------

    private static string RepoRoot =>
        Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));

    private static string ParsedCellFixture =>
        Path.Combine(RepoRoot, "tests", "fixtures", "parsed-cell", "valid.json");

    private static string PlanFixture =>
        Path.Combine(RepoRoot, "tests", "fixtures", "plan-recommendations", "valid.json");

    private static readonly DateTimeOffset FixedTs =
        new(2026, 1, 1, 0, 0, 0, TimeSpan.Zero);

    // -----------------------------------------------------------------------
    // Pipeline helpers
    // -----------------------------------------------------------------------

    private static PlanningRuleResult BuildRuleResult(out int width, out int height)
    {
        var loaded = ParsedCellLoader.Load(ParsedCellFixture);
        Assert.True(loaded.IsValid, string.Join("; ", loaded.Errors));

        width  = loaded.Grid!.Width;
        height = loaded.Grid!.Height;

        var codeToKind = loaded.Document!.Counts
            .ToDictionary(c => c.Code[0], c => c.Kind)
            .AsReadOnly();

        var regions    = RegionExtractor.Extract(loaded.Grid!, codeToKind);
        var primitives = PrimitiveClassifier.Classify(regions);
        return PlanningRuleEngine.Evaluate(primitives);
    }

    private string GenerateToTemp()
    {
        var result = BuildRuleResult(out var w, out var h);
        var (jsonPath, _) = PlanningArtifactWriter.Write(
            _tempDir, w, h, ParsedCellFixture, "cross-verification",
            result, overrideGeneratedAt: FixedTs);
        return jsonPath;
    }

    /// <summary>
    /// Ensures the reference fixture exists.
    /// On first run, generates and saves it — developer must commit it.
    /// </summary>
    private void EnsureFixture()
    {
        if (File.Exists(PlanFixture)) return;
        var jsonPath = GenerateToTemp();
        Directory.CreateDirectory(Path.GetDirectoryName(PlanFixture)!);
        File.Copy(jsonPath, PlanFixture, overwrite: false);
    }

    // -----------------------------------------------------------------------
    // Test 1: header fields
    // -----------------------------------------------------------------------

    [Fact]
    public void CrossVerify_HeaderFieldsMatch()
    {
        EnsureFixture();
        var gen = JsonDocument.Parse(File.ReadAllText(GenerateToTemp())).RootElement;
        var ref_ = JsonDocument.Parse(File.ReadAllText(PlanFixture)).RootElement;

        Assert.Equal(
            ref_.GetProperty("schema").GetString(),
            gen.GetProperty("schema").GetString());

        Assert.Equal(
            ref_.GetProperty("claim_boundary").GetString(),
            gen.GetProperty("claim_boundary").GetString());

        Assert.Equal(
            ref_.GetProperty("width").GetInt32(),
            gen.GetProperty("width").GetInt32());

        Assert.Equal(
            ref_.GetProperty("height").GetInt32(),
            gen.GetProperty("height").GetInt32());

        Assert.Equal(
            ref_.GetProperty("primitive_count").GetInt32(),
            gen.GetProperty("primitive_count").GetInt32());

        Assert.Equal(
            ref_.GetProperty("recommendation_count").GetInt32(),
            gen.GetProperty("recommendation_count").GetInt32());

        Assert.Equal(
            ref_.GetProperty("warning_count").GetInt32(),
            gen.GetProperty("warning_count").GetInt32());

        var refT = ref_.GetProperty("thresholds_used");
        var genT = gen.GetProperty("thresholds_used");
        Assert.Equal(refT.GetProperty("tiny_building_pixel_threshold").GetInt32(),
                     genT.GetProperty("tiny_building_pixel_threshold").GetInt32());
        Assert.Equal(refT.GetProperty("large_ground_pixel_threshold").GetInt32(),
                     genT.GetProperty("large_ground_pixel_threshold").GetInt32());
    }

    // -----------------------------------------------------------------------
    // Test 2: all recommendations match
    // -----------------------------------------------------------------------

    [Fact]
    public void CrossVerify_AllRecommendationsMatch()
    {
        EnsureFixture();
        var gen  = JsonDocument.Parse(File.ReadAllText(GenerateToTemp())).RootElement;
        var ref_ = JsonDocument.Parse(File.ReadAllText(PlanFixture)).RootElement;

        var genRecs = gen.GetProperty("recommendations").EnumerateArray().ToList();
        var refRecs = ref_.GetProperty("recommendations").EnumerateArray().ToList();

        Assert.Equal(refRecs.Count, genRecs.Count);

        for (int i = 0; i < refRecs.Count; i++)
        {
            var r = refRecs[i];
            var g = genRecs[i];
            var lbl = $"rec[{i}]";

            Assert.Equal(r.GetProperty("recommendation_id").GetInt32(),
                         g.GetProperty("recommendation_id").GetInt32());

            Assert.Equal(r.GetProperty("recommendation_type").GetString(),
                         g.GetProperty("recommendation_type").GetString());

            Assert.Equal(r.GetProperty("severity").GetString(),
                         g.GetProperty("severity").GetString());

            Assert.Equal(r.GetProperty("planning_role").GetString(),
                         g.GetProperty("planning_role").GetString());

            Assert.Equal(r.GetProperty("source_primitive_id").GetInt32(),
                         g.GetProperty("source_primitive_id").GetInt32());

            Assert.Equal(r.GetProperty("primitive_type").GetString(),
                         g.GetProperty("primitive_type").GetString());

            Assert.Equal(r.GetProperty("pixel_count").GetInt32(),
                         g.GetProperty("pixel_count").GetInt32());

            Assert.Equal(r.GetProperty("message").GetString(),
                         g.GetProperty("message").GetString());

            // bounds: compare if present in both
            var rHasBounds = r.TryGetProperty("bounds", out var rBounds);
            var gHasBounds = g.TryGetProperty("bounds", out var gBounds);
            Assert.Equal(rHasBounds, gHasBounds);
            if (rHasBounds && rBounds.ValueKind != JsonValueKind.Null &&
                gBounds.ValueKind != JsonValueKind.Null)
            {
                Assert.Equal(rBounds.GetProperty("x").GetInt32(),
                             gBounds.GetProperty("x").GetInt32());
                Assert.Equal(rBounds.GetProperty("y").GetInt32(),
                             gBounds.GetProperty("y").GetInt32());
                Assert.Equal(rBounds.GetProperty("width").GetInt32(),
                             gBounds.GetProperty("width").GetInt32());
                Assert.Equal(rBounds.GetProperty("height").GetInt32(),
                             gBounds.GetProperty("height").GetInt32());
            }
        }
    }

    // -----------------------------------------------------------------------
    // Test 3: summary matches
    // -----------------------------------------------------------------------

    [Fact]
    public void CrossVerify_SummaryMatch()
    {
        EnsureFixture();
        var gen  = JsonDocument.Parse(File.ReadAllText(GenerateToTemp())).RootElement;
        var ref_ = JsonDocument.Parse(File.ReadAllText(PlanFixture)).RootElement;

        var gSum = gen.GetProperty("summary");
        var rSum = ref_.GetProperty("summary");

        Assert.Equal(rSum.GetProperty("total_pixels").GetInt32(),
                     gSum.GetProperty("total_pixels").GetInt32());

        Assert.Equal(rSum.GetProperty("primitive_count").GetInt32(),
                     gSum.GetProperty("primitive_count").GetInt32());

        Assert.Equal(rSum.GetProperty("recommendation_count").GetInt32(),
                     gSum.GetProperty("recommendation_count").GetInt32());

        Assert.Equal(rSum.GetProperty("warning_count").GetInt32(),
                     gSum.GetProperty("warning_count").GetInt32());

        // counts_by_recommendation_type — all keys and values must match
        var rByType = rSum.GetProperty("counts_by_recommendation_type")
            .EnumerateObject().ToDictionary(p => p.Name, p => p.Value.GetInt32());
        var gByType = gSum.GetProperty("counts_by_recommendation_type")
            .EnumerateObject().ToDictionary(p => p.Name, p => p.Value.GetInt32());

        Assert.Equal(rByType.Count, gByType.Count);
        foreach (var (key, val) in rByType)
            Assert.Equal(val, gByType[key]);

        // counts_by_severity
        var rBySev = rSum.GetProperty("counts_by_severity")
            .EnumerateObject().ToDictionary(p => p.Name, p => p.Value.GetInt32());
        var gBySev = gSum.GetProperty("counts_by_severity")
            .EnumerateObject().ToDictionary(p => p.Name, p => p.Value.GetInt32());

        Assert.Equal(rBySev.Count, gBySev.Count);
        foreach (var (key, val) in rBySev)
            Assert.Equal(val, gBySev[key]);
    }
}
