# generate-worldgen-prefab-dump-lua.ps1
# Writes a WorldGen probe Lua that dumps all worldgen.prefabs keys at runtime.
#
# Purpose: MAP-22B - discover road-like prefab keys beyond the two currently proven
# (normal_road_WE_00, highway_NS_00). The probe does not alter terrain.
#
# Generated Lua:
#   - Sets worldgen["static_modules"] = {} so no terrain is altered
#   - Iterates worldgen.prefabs and prints each key
#   - Filters road-like keys (road/highway/street/alley/lane/path/rail/bridge/WE/NS)
#   - Prints machine-readable markers for harvest
#
# Output format (appears in PZ log/console):
#   PZMAPFORGE_PREFAB_DUMP_LOADED
#   PZMAPFORGE_PREFAB_KEY=<key>
#   PZMAPFORGE_ROADLIKE_PREFAB_KEY=<key>
#   PZMAPFORGE_PREFAB_COUNT=<n>
#   PZMAPFORGE_ROADLIKE_PREFAB_COUNT=<n>
#
# This is a discovery probe only. No prefab is considered runtime-proven by this probe.
# Any discovered key must be added to WorldGenRegistry and visually confirmed (MAP-22C).
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\generate-worldgen-prefab-dump-lua.ps1
#   powershell -ExecutionPolicy Bypass -File scripts\generate-worldgen-prefab-dump-lua.ps1 -OutputDir <path>

param(
    [string]$OutputDir = ""
)

$repoRoot = $PSScriptRoot | Split-Path -Parent | Split-Path -Parent | Split-Path -Parent

if ([string]::IsNullOrWhiteSpace($OutputDir)) {
    $OutputDir = Join-Path $repoRoot ".local\deadmtl-authoring\worldgen-prefab-dump"
}

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

$luaPath = Join-Path $OutputDir "WorldGenOverride.lua"

Write-Host "Generating WorldGen prefab dump probe at: $luaPath"
Write-Host ""

# ---------------------------------------------------------------------------
# Lua content (single-quoted heredoc -- no variable interpolation)
# All characters are ASCII. Written with ASCII encoding, no BOM.
# ---------------------------------------------------------------------------
$luaContent = @'
-- PZMAPFORGE_PREFAB_DUMP_LOADED
-- MAP22B WorldGen prefab discovery probe
-- Generated by: generate-worldgen-prefab-dump-lua.ps1
-- Purpose: enumerate all worldgen.prefabs keys at PZ runtime
-- This probe does not alter terrain. worldgen["static_modules"] is empty.
-- Harvest output with: harvest-worldgen-prefab-dump-logs.ps1
--
-- Road-like filter criteria (broad; review results manually):
--   road, highway, street, alley, lane, path, rail, bridge, we, ns

print("PZMAPFORGE_PREFAB_DUMP_LOADED")

-- Empty static_modules so no terrain is altered during this probe run
worldgen["static_modules"] = {}

-- Collect all keys from worldgen.prefabs
local prefabKeys = {}
for k in pairs(worldgen.prefabs) do
    prefabKeys[#prefabKeys + 1] = k
end
table.sort(prefabKeys)

-- Print all known prefab keys
for _, k in ipairs(prefabKeys) do
    print("PZMAPFORGE_PREFAB_KEY=" .. k)
end

-- Filter road-like keys (case-insensitive substring match)
-- Filters: road, highway, street, alley, lane, path, rail, bridge, we, ns
-- Note: "we" and "ns" are broad and may produce false positives; review manually.
local roadLikeKeys = {}
for _, k in ipairs(prefabKeys) do
    local lk = string.lower(k)
    if string.find(lk, "road") or
       string.find(lk, "highway") or
       string.find(lk, "street") or
       string.find(lk, "alley") or
       string.find(lk, "lane") or
       string.find(lk, "path") or
       string.find(lk, "rail") or
       string.find(lk, "bridge") or
       string.find(lk, "we") or
       string.find(lk, "ns") then
        roadLikeKeys[#roadLikeKeys + 1] = k
    end
end

for _, k in ipairs(roadLikeKeys) do
    print("PZMAPFORGE_ROADLIKE_PREFAB_KEY=" .. k)
end

-- Summary counts
print("PZMAPFORGE_PREFAB_COUNT=" .. #prefabKeys)
print("PZMAPFORGE_ROADLIKE_PREFAB_COUNT=" .. #roadLikeKeys)
'@

# Write as ASCII, no BOM
[System.IO.File]::WriteAllText($luaPath, $luaContent, [System.Text.Encoding]::ASCII)

# Byte-check
$bytes       = [System.IO.File]::ReadAllBytes($luaPath)
$hasBom      = ($bytes.Length -ge 3) -and ($bytes[0] -eq 0xEF) -and ($bytes[1] -eq 0xBB) -and ($bytes[2] -eq 0xBF)
$hasNonAscii = ($bytes | Where-Object { $_ -gt 127 }).Count -gt 0

if ($hasBom)      { Write-Error "FAIL: probe Lua has BOM"; exit 1 }
if ($hasNonAscii) { Write-Error "FAIL: probe Lua has non-ASCII bytes"; exit 1 }

Write-Host "  OK  WorldGenOverride.lua ($($bytes.Length) bytes, ASCII, no BOM)"
Write-Host ""
Write-Host "Preview (first 20 lines):"
Get-Content $luaPath -TotalCount 20 | ForEach-Object { Write-Host "  $_" }
Write-Host ""
Write-Host "Install with:"
Write-Host "  run-worldgen-prefab-dump.ps1 -Install"
Write-Host "Harvest results after PZ run with:"
Write-Host "  harvest-worldgen-prefab-dump-logs.ps1"
