# generate-spawn-centered-proof-pack.ps1
# Generates a complete spawn-centered runtime proof pack under .local/.
# All painted features are within 50 tiles of spawn (10650, 8250) so they
# are visible immediately on first spawn without walking or searching.
#
# Spawn reference: world tile (10650, 8250)
# Grid origin:     origin_x=10580, origin_y=8200 (190x140 tiles)
#
# Pixel coordinate formula:
#   pixel_x = world_x - 10580
#   pixel_y = world_y - 8200
#
# Painted System 1 features (world tile coords):
#   roads_major  normal_road_WE_00  x=10618..10682, y=8248..8252  -> px(38,48) 65x5
#   shore        sand_bank          x=10632..10668, y=8238..8265  -> px(52,38) 37x28
#   parks_forest birch_forest       x=10608..10630, y=8238..8272  -> px(28,38) 23x35
#   water        (entire canvas)    x=10670..10690 visible area   -> px(90,38) 21x28 (base fill)
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\generate-spawn-centered-proof-pack.ps1
#   powershell -ExecutionPolicy Bypass -File scripts\generate-spawn-centered-proof-pack.ps1 -OutputDir <path>

param(
    [string]$OutputDir = ""
)

Add-Type -AssemblyName System.Drawing

$repoRoot = $PSScriptRoot | Split-Path -Parent | Split-Path -Parent | Split-Path -Parent

if ([string]::IsNullOrWhiteSpace($OutputDir)) {
    $OutputDir = Join-Path $repoRoot ".local\deadmtl-authoring\spawn-centered-proof-pack"
}

$layersDir   = Join-Path $OutputDir "layers"
$palettesDir = Join-Path $OutputDir "palettes"
$scriptsDir  = Join-Path $OutputDir "scripts"

New-Item -ItemType Directory -Force -Path $layersDir   | Out-Null
New-Item -ItemType Directory -Force -Path $palettesDir | Out-Null
New-Item -ItemType Directory -Force -Path $scriptsDir  | Out-Null

Write-Host "Generating spawn-centered proof pack at: $OutputDir"
Write-Host "Spawn reference: world tile 10650, 8250"
Write-Host ""

# ---------------------------------------------------------------------------
# Canvas dimensions (must match validator contract)
# ---------------------------------------------------------------------------
$W = 190
$H = 140

# Map ID for this proof pack
$MAP_ID = "deadmtl_spawn_centered_proof_v1"

# ---------------------------------------------------------------------------
# Palette colors (match palettes/worldgen-png-palette.json)
# ---------------------------------------------------------------------------
$colorWater  = [System.Drawing.Color]::FromArgb(255,   0,   0, 255)  # #0000FF biome:water
$colorShore  = [System.Drawing.Color]::FromArgb(255, 216, 192, 128)  # #D8C080 biome:sand_bank
$colorForest = [System.Drawing.Color]::FromArgb(255,  32, 112,  32)  # #207020 biome:birch_forest
$colorRoad   = [System.Drawing.Color]::FromArgb(255, 255, 102,   0)  # #FF6600 prefab:normal_road_WE_00
$transparent = [System.Drawing.Color]::FromArgb(0,    0,   0,   0)

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------
function New-Transparent([int]$w, [int]$h) {
    $bmp = New-Object System.Drawing.Bitmap $w, $h
    $g   = [System.Drawing.Graphics]::FromImage($bmp)
    $g.Clear($transparent)
    $g.Dispose()
    return $bmp
}

function Save-Bmp([System.Drawing.Bitmap]$bmp, [string]$path) {
    $bmp.Save($path, [System.Drawing.Imaging.ImageFormat]::Png)
    $bmp.Dispose()
    Write-Host "  OK  $([System.IO.Path]::GetFileName($path))"
}

# ---------------------------------------------------------------------------
# Project manifest
# ---------------------------------------------------------------------------
Write-Host "Writing project manifest..."
$manifest = @"
{
  "format": "pzmapforge.worldgen.project.v1",
  "map_id": "$MAP_ID",
  "origin_x": 10580,
  "origin_y": 8200,
  "width": $W,
  "height": $H,
  "layers": [
    {
      "id": "water",
      "path": "layers/water.png",
      "palette": "palettes/worldgen-png-palette.json",
      "priority": 10
    },
    {
      "id": "shore",
      "path": "layers/shore.png",
      "palette": "palettes/worldgen-png-palette.json",
      "priority": 20
    },
    {
      "id": "parks_forest",
      "path": "layers/parks_forest.png",
      "palette": "palettes/worldgen-png-palette.json",
      "priority": 30
    },
    {
      "id": "roads_major",
      "path": "layers/roads_major.png",
      "palette": "palettes/worldgen-png-palette.json",
      "priority": 50
    }
  ]
}
"@
Set-Content -Path (Join-Path $OutputDir "deadmtl_worldgen_project.json") -Value $manifest -Encoding UTF8
Write-Host "  OK  deadmtl_worldgen_project.json"

# ---------------------------------------------------------------------------
# README
# ---------------------------------------------------------------------------
$readme = @"
# DeadMTL Spawn-Centered Proof Pack

Map ID: $MAP_ID
Generated by: generate-spawn-centered-proof-pack.ps1
Claim boundary: authoring artifact only. Not a public mod package.

## Purpose

All painted features are within 50 tiles of spawn tile (10650, 8250).
Runtime test features are visible immediately on spawn without walking.

## Spawn reference

  World tile: 10650, 8250
  Grid origin: 10580, 8200

## Painted features (world tile coordinates)

  water        base fill     entire canvas    (water shows wherever not overridden)
  shore        sand_bank     x=10632..10668   y=8238..8265
  parks_forest birch_forest  x=10608..10630   y=8238..8272
  roads_major  road WE_00    x=10618..10682   y=8248..8252  (passes through spawn)
  water area   (reference)   x=10670..10690   y=8238..8265  (base water visible here)

## Expected visual at spawn

  - Road crossing at y=8248..8252 (passes immediately under player at 10650,8250)
  - Shore/sand patch north-west of spawn
  - Birch forest patch west of spawn
  - Open water east of shore
"@
Set-Content -Path (Join-Path $OutputDir "README.md") -Value $readme -Encoding UTF8
Write-Host "  OK  README.md"

# ---------------------------------------------------------------------------
# Palette files
# ---------------------------------------------------------------------------
Write-Host "Writing palette files..."

$worldgenPalette = @"
{
  "format": "pzmapforge.worldgen.png-palette.v1",
  "entries": [
    { "color": "#0000FF", "type": "biome",  "key": "water" },
    { "color": "#D8C080", "type": "biome",  "key": "sand_bank" },
    { "color": "#207020", "type": "biome",  "key": "birch_forest" },
    { "color": "#FF6600", "type": "prefab", "key": "normal_road_WE_00" },
    { "color": "#CC3300", "type": "prefab", "key": "highway_NS_00" }
  ]
}
"@
Set-Content -Path (Join-Path $palettesDir "worldgen-png-palette.json") -Value $worldgenPalette -Encoding UTF8
Set-Content -Path (Join-Path $palettesDir "zoning-palette.json")   -Value '{"_note":"FUTURE"}' -Encoding UTF8
Set-Content -Path (Join-Path $palettesDir "metadata-palette.json") -Value '{"_note":"FUTURE"}' -Encoding UTF8
Write-Host "  OK  palettes (3)"

# ---------------------------------------------------------------------------
# Script stubs (required by validator contract)
# ---------------------------------------------------------------------------
Set-Content -Path (Join-Path $scriptsDir "generate-empty-layer-pack.ps1") -Value "# stub - see parent pack" -Encoding UTF8
Set-Content -Path (Join-Path $scriptsDir "validate-layer-pack.ps1")        -Value "# stub - see parent pack" -Encoding UTF8
Write-Host "  OK  script stubs"

# ---------------------------------------------------------------------------
# System 1 layers: spawn-centered paint
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "Generating System 1 layers..."

# water.png: base fill - entire canvas
# Water visible area near spawn: world x=10670..10690, y=8238..8265
#   pixel: x=90, y=38 (reference area - shown by base fill, no explicit paint needed)
$bmp = New-Transparent $W $H
$g   = [System.Drawing.Graphics]::FromImage($bmp)
$g.Clear($colorWater)
$g.Dispose()
Save-Bmp $bmp (Join-Path $layersDir "water.png")

# shore.png: sand_bank
# World: x=10632..10668, y=8238..8265 -> pixel: x=52, y=38, width=37, height=28
$bmp = New-Transparent $W $H
$g   = [System.Drawing.Graphics]::FromImage($bmp)
$b   = New-Object System.Drawing.SolidBrush($colorShore)
$g.FillRectangle($b, 52, 38, 37, 28)   # world x=10632..10668, y=8238..8265
$b.Dispose(); $g.Dispose()
Save-Bmp $bmp (Join-Path $layersDir "shore.png")

# parks_forest.png: birch_forest
# World: x=10608..10630, y=8238..8272 -> pixel: x=28, y=38, width=23, height=35
$bmp = New-Transparent $W $H
$g   = [System.Drawing.Graphics]::FromImage($bmp)
$b   = New-Object System.Drawing.SolidBrush($colorForest)
$g.FillRectangle($b, 28, 38, 23, 35)   # world x=10608..10630, y=8238..8272
$b.Dispose(); $g.Dispose()
Save-Bmp $bmp (Join-Path $layersDir "parks_forest.png")

# roads_major.png: normal_road_WE_00 crossing spawn
# World: x=10618..10682, y=8248..8252 -> pixel: x=38, y=48, width=65, height=5
$bmp = New-Transparent $W $H
$g   = [System.Drawing.Graphics]::FromImage($bmp)
$b   = New-Object System.Drawing.SolidBrush($colorRoad)
$g.FillRectangle($b, 38, 48, 65, 5)    # world x=10618..10682, y=8248..8252
$b.Dispose(); $g.Dispose()
Save-Bmp $bmp (Join-Path $layersDir "roads_major.png")

# ---------------------------------------------------------------------------
# System 2-4 placeholder layers: fully transparent
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "Generating placeholder layers (transparent)..."

$placeholders = @(
    "roads_local.png",
    "zones_residential.png",
    "zones_commercial.png",
    "zones_industrial.png",
    "placed_buildings.png",
    "props.png",
    "npc_zones.png",
    "ownership.png"
)

foreach ($name in $placeholders) {
    $bmp = New-Transparent $W $H
    Save-Bmp $bmp (Join-Path $layersDir $name)
}

Write-Host ""
Write-Host "Pack generated: $OutputDir"
Write-Host ""
Write-Host "Compile with:"
Write-Host "  dotnet run --project src\PZMapForge.Cli --configuration Release --no-build -- ``"
Write-Host "    deadmtl-authoring-build ``"
Write-Host "    --input `"$OutputDir`" ``"
Write-Host "    --output .local\deadmtl-authoring\spawn-centered-proof"
