# generate-road-layer-placeholders.ps1
# Generates transparent placeholder PNGs for road layers under .local/.
#
# This script is an authoring scaffold only.
# It does NOT produce WorldGen output.
# It does NOT run any compile step.
# It does NOT write to any PZ game folder.
#
# Purpose:
#   Establishes the road layer file structure for:
#     roads_highway.png   - highway (10-14 px wide at 1px=1m)
#     roads_major.png     - arterial/major roads (8-10 px)
#     roads_local.png     - local streets (5-7 px)  [SYSTEM_2_REQUIRED]
#     roads_alleys.png    - Montreal ruelles/alleys (3-4 px) [SYSTEM_2_REQUIRED]
#     roads_service.png   - service lanes/parking access (2-5 px) [SYSTEM_2_REQUIRED]
#
# Compiler support status (see road-layers-contract.json):
#   roads_highway : WORLDGEN_LIMITED (highway_NS_00 proven; WE/turns not proven)
#   roads_major   : WORLDGEN_LIMITED (normal_road_WE_00 proven; NS/turns not proven)
#   roads_local   : SYSTEM_2_REQUIRED (no local street prefab proven)
#   roads_alleys  : SYSTEM_2_REQUIRED (no alley/ruelle prefab proven)
#   roads_service : SYSTEM_2_REQUIRED (no service lane prefab proven)
#
# Canvas: 220x170 tiles, origin_x=10580, origin_y=8200
# Spawn:  world (10650, 8250) = pixel (70, 50)
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\generate-road-layer-placeholders.ps1
#   powershell -ExecutionPolicy Bypass -File scripts\generate-road-layer-placeholders.ps1 -OutputDir <path>

param(
    [string]$OutputDir = ""
)

Add-Type -AssemblyName System.Drawing

$repoRoot = $PSScriptRoot | Split-Path -Parent | Split-Path -Parent | Split-Path -Parent

if ([string]::IsNullOrWhiteSpace($OutputDir)) {
    $OutputDir = Join-Path $repoRoot ".local\deadmtl-authoring\road-layer-placeholders"
}

$layersDir = Join-Path $OutputDir "layers"
New-Item -ItemType Directory -Force -Path $layersDir | Out-Null

Write-Host "Generating road layer placeholders at: $OutputDir"
Write-Host "All PNGs are transparent placeholders. No WorldGen output is produced."
Write-Host ""

$W           = 220
$H           = 170
$transparent = [System.Drawing.Color]::FromArgb(0, 0, 0, 0)

function New-TransparentPng([string]$path, [int]$w, [int]$h) {
    $bmp = New-Object System.Drawing.Bitmap $w, $h
    $g   = [System.Drawing.Graphics]::FromImage($bmp)
    $g.Clear($transparent)
    $g.Dispose()
    $bmp.Save($path, [System.Drawing.Imaging.ImageFormat]::Png)
    $bmp.Dispose()
    Write-Host "  OK  $([System.IO.Path]::GetFileName($path)) ($w x $h, transparent placeholder)"
}

# ---------------------------------------------------------------------------
# Road layer placeholders
# ---------------------------------------------------------------------------

# WORLDGEN_LIMITED: highway_NS_00 proven; WE variant and turns not yet proven
New-TransparentPng (Join-Path $layersDir "roads_highway.png") $W $H

# WORLDGEN_LIMITED: normal_road_WE_00 proven; NS variant and turns not yet proven
New-TransparentPng (Join-Path $layersDir "roads_major.png") $W $H

# SYSTEM_2_REQUIRED: no local street prefab proven in WorldGen
New-TransparentPng (Join-Path $layersDir "roads_local.png") $W $H

# SYSTEM_2_REQUIRED: no alley/ruelle prefab proven in WorldGen
New-TransparentPng (Join-Path $layersDir "roads_alleys.png") $W $H

# SYSTEM_2_REQUIRED: no service lane prefab proven in WorldGen
New-TransparentPng (Join-Path $layersDir "roads_service.png") $W $H

# ---------------------------------------------------------------------------
# README
# ---------------------------------------------------------------------------
Set-Content -Path (Join-Path $OutputDir "README.md") -Value @"
# Road Layer Placeholders

Generated by: generate-road-layer-placeholders.ps1
Canvas: ${W}x${H} tiles, origin_x=10580, origin_y=8200

## Contents

These files are transparent placeholder PNGs only.
They are NOT compiled into WorldGen output.
They are NOT proof artifacts.
They establish the road layer file structure for future authoring.

## Compiler support status

| Layer | Status | Width (px) |
|---|---|---|
| roads_highway.png | WORLDGEN_LIMITED | 10-14 |
| roads_major.png | WORLDGEN_LIMITED | 8-10 |
| roads_local.png | SYSTEM_2_REQUIRED | 5-7 |
| roads_alleys.png | SYSTEM_2_REQUIRED | 3-4 |
| roads_service.png | SYSTEM_2_REQUIRED | 2-5 |

WORLDGEN_LIMITED: a subset of this road type is compiler-supported (one direction only;
turns and intersections not proven).

SYSTEM_2_REQUIRED: no proven WorldGen prefab covers this road type. Requires System 2
static tile overlay or future prefab discovery (MAP-22B).

## What to do next

1. Paint road geometry into these placeholder PNGs using a pixel editor.
   Use 1 pixel = 1 meter = 1 PZ tile scale.

2. For WORLDGEN_LIMITED layers: only paint the proven direction.
   - roads_highway.png: NS strips only (highway_NS_00)
   - roads_major.png: WE strips only (normal_road_WE_00)
   Turns and intersections cannot be compiled until new prefab keys are proven (MAP-22B).

3. For SYSTEM_2_REQUIRED layers: defer to System 2 static tile overlay (MAP-22D).
   Do not attempt to compile these into WorldGen output.

See docs/authoring/DEADMTL_SMALL_ROADS_ALLEYS_CONTRACT.md for the full contract.
"@ -Encoding UTF8
Write-Host "  OK  README.md"

Write-Host ""
Write-Host "Road layer placeholders written to: $layersDir"
Write-Host ""
Write-Host "Contract: examples\deadmtl-layer-pack\road-layers-contract.json"
Write-Host "Docs:     docs\authoring\DEADMTL_SMALL_ROADS_ALLEYS_CONTRACT.md"
