# run-worldgen-palette-proof-build.ps1
# End-to-end WorldGen palette proof build:
#   1. Generate proof pack (swatch PNGs for all 12 palette colors)
#   2. Generate palette color charts
#   3. compile-worldgen-project -> worldgen_layers.json
#   4. compile-worldgen -> WorldGenOverride.lua
#   5. Print Lua preview and expected runtime markers
#   6. Optionally install Lua to game folder (-Install)
#
# IMPORTANT: By default this script does NOT write to any PZ game folders.
# Pass -Install to perform the optional install step.
#
# Spawn reference: world tile 10650, 8250 = pixel (70, 50)
# Map ID: deadmtl_worldgen_palette_probe_v1
#
# Usage (no install):
#   powershell -ExecutionPolicy Bypass -File scripts\run-worldgen-palette-proof-build.ps1
#
# Usage (with install):
#   powershell -ExecutionPolicy Bypass -File scripts\run-worldgen-palette-proof-build.ps1 -Install

param(
    [switch]$Install
)

$ErrorActionPreference = "Stop"

$repoRoot  = $PSScriptRoot | Split-Path -Parent | Split-Path -Parent | Split-Path -Parent
$packDir   = Join-Path $repoRoot ".local\deadmtl-authoring\worldgen-palette-proof-pack"
$outputDir = Join-Path $repoRoot ".local\deadmtl-authoring\worldgen-palette-proof"
$projectFile = Join-Path $packDir "worldgen_palette_probe_project.json"
$manifestPath = Join-Path $outputDir "worldgen_layers.json"
$luaPath      = Join-Path $outputDir "WorldGenOverride.lua"

$MAP_ID = "deadmtl_worldgen_palette_probe_v1"

New-Item -ItemType Directory -Force -Path $outputDir | Out-Null

# ---------------------------------------------------------------------------
# Step 1: Generate proof pack
# ---------------------------------------------------------------------------
Write-Host "=== Step 1: Generate WorldGen palette proof pack ==="
Write-Host ""

$generateScript = Join-Path $PSScriptRoot "generate-worldgen-palette-proof-pack.ps1"
& powershell -ExecutionPolicy Bypass -File $generateScript -OutputDir $packDir
if ($LASTEXITCODE -ne 0) {
    Write-Error "generate-worldgen-palette-proof-pack.ps1 failed (exit $LASTEXITCODE)"
    exit 1
}

# ---------------------------------------------------------------------------
# Step 2: Palette charts (already generated by proof pack script, confirm)
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "=== Step 2: Palette charts ==="
Write-Host ""

$chartPath     = Join-Path $packDir "palettes\worldgen-png-palette.chart.png"
$swatchesPath  = Join-Path $packDir "palettes\worldgen-png-palette.swatches.txt"

if (Test-Path $chartPath)    { Write-Host "  OK  $chartPath" }
else                         { Write-Warning "Chart PNG not found: $chartPath" }
if (Test-Path $swatchesPath) { Write-Host "  OK  $swatchesPath" }
else                         { Write-Warning "Swatches TXT not found: $swatchesPath" }

# ---------------------------------------------------------------------------
# Step 3: compile-worldgen-project
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "=== Step 3: compile-worldgen-project ==="
Write-Host ""

& dotnet run `
    --project (Join-Path $repoRoot "src\PZMapForge.Cli") `
    --configuration Release `
    --no-build `
    -- `
    compile-worldgen-project `
    --input $projectFile `
    --output $manifestPath

if ($LASTEXITCODE -ne 0) {
    Write-Error "compile-worldgen-project failed (exit $LASTEXITCODE)"
    exit 1
}
Write-Host "  OK  $manifestPath"

# ---------------------------------------------------------------------------
# Step 4: compile-worldgen
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "=== Step 4: compile-worldgen ==="
Write-Host ""

& dotnet run `
    --project (Join-Path $repoRoot "src\PZMapForge.Cli") `
    --configuration Release `
    --no-build `
    -- `
    compile-worldgen `
    --input $manifestPath `
    --output $luaPath

if ($LASTEXITCODE -ne 0) {
    Write-Error "compile-worldgen failed (exit $LASTEXITCODE)"
    exit 1
}
Write-Host "  OK  $luaPath"

# ---------------------------------------------------------------------------
# Step 5: Lua preview and expected markers
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "=== Step 5: Lua preview (first 30 lines) ==="
Write-Host ""

Get-Content $luaPath -TotalCount 30 | ForEach-Object { Write-Host "  $_" }

# Count modules
$luaContent  = Get-Content $luaPath -Raw
$moduleCount = ([regex]::Matches($luaContent, "position\s*=\s*\{")).Count

Write-Host ""
Write-Host "=== Expected runtime markers ==="
Write-Host ""
Write-Host "  PZMAPFORGE_WORLDGENOVERRIDE_MAP_ID=$MAP_ID"
Write-Host "  PZMAPFORGE_WORLDGENOVERRIDE_LOADED"
Write-Host "  PZMAPFORGE_WORLDGENOVERRIDE_MODULE_COUNT=$moduleCount"
Write-Host ""
Write-Host "Spawn reference:    world tile 10650, 8250 = pixel (70, 50)"
Write-Host "Biome rows:         pixel y=5..30 (world y=8205..8230)"
Write-Host "Road WE:            pixel y=48..55 (world y=8248..8255)"
Write-Host "Highway NS:         pixel x=130..137 (world x=10710..10717)"

# Byte check
$luaBytes    = [System.IO.File]::ReadAllBytes($luaPath)
$hasBom      = ($luaBytes.Length -ge 3) -and ($luaBytes[0] -eq 0xEF) -and ($luaBytes[1] -eq 0xBB) -and ($luaBytes[2] -eq 0xBF)
$hasNonAscii = ($luaBytes | Where-Object { $_ -gt 127 }).Count -gt 0

Write-Host ""
Write-Host "Lua byte check:     BOM=$hasBom  Non-ASCII=$hasNonAscii"

if ($hasBom -or $hasNonAscii) {
    Write-Error "Lua byte check FAILED"
    exit 1
}

# ---------------------------------------------------------------------------
# No-install exit
# ---------------------------------------------------------------------------
if (-not $Install) {
    Write-Host ""
    Write-Host "=== Install step: SKIPPED (pass -Install to install) ==="
    Write-Host ""
    Write-Host "To install manually, copy:"
    Write-Host "  Source: $luaPath"
    Write-Host "  Dest:   D:\Program Files (x86)\Steam\steamapps\common\ProjectZomboid\media\maps\pzmapforge_build42_candidate_v4_001\WorldGenOverride.lua"
    Write-Host ""
    Write-Host "Then clear save folder:"
    Write-Host "  C:\Users\Palmacede\Zomboid\Saves\Multiplayer\PZMF_B42_MAP9F_NO_MULDRAUGH_001"
    exit 0
}

# ---------------------------------------------------------------------------
# Install block — only runs when -Install is explicitly passed
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "=== Install (-Install mode) ==="
Write-Host ""

$gameMapDir = "D:\Program Files (x86)\Steam\steamapps\common\ProjectZomboid\media\maps\pzmapforge_build42_candidate_v4_001"
$destLua    = Join-Path $gameMapDir "WorldGenOverride.lua"
$saveFolder = "C:\Users\Palmacede\Zomboid\Saves\Multiplayer\PZMF_B42_MAP9F_NO_MULDRAUGH_001"

if (-not (Test-Path $gameMapDir)) {
    Write-Error "Game map dir not found: $gameMapDir"
    exit 1
}

# Backup existing Lua
if (Test-Path $destLua) {
    $ts         = (Get-Date -Format "yyyyMMdd-HHmmss")
    $backupPath = "$destLua.$ts.bak"
    Copy-Item -Path $destLua -Destination $backupPath
    Write-Host "  Backed up: $backupPath"
}

# Install
Copy-Item -Path $luaPath -Destination $destLua -Force
Write-Host "  Installed: $destLua"

# Byte-check installed file
$installedBytes = [System.IO.File]::ReadAllBytes($destLua)
$instBom        = ($installedBytes.Length -ge 3) -and ($installedBytes[0] -eq 0xEF) -and ($installedBytes[1] -eq 0xBB) -and ($installedBytes[2] -eq 0xBF)
$instNonAscii   = ($installedBytes | Where-Object { $_ -gt 127 }).Count -gt 0

if ($instBom)      { Write-Error "VERDICT: FAIL — installed Lua has BOM"; exit 1 }
if ($instNonAscii) { Write-Error "VERDICT: FAIL — installed Lua has non-ASCII bytes"; exit 1 }
Write-Host "  Byte check: BOM=false, Non-ASCII=false"

# Clear save folder
if (Test-Path $saveFolder) {
    Remove-Item -Recurse -Force $saveFolder
    Write-Host "  Cleared save folder: $saveFolder"
} else {
    Write-Host "  Save folder not found (already clear): $saveFolder"
}

Write-Host ""
Write-Host "VERDICT: MAP21A_WORLDGEN_PALETTE_PROOF_INSTALLED_RESTART_REQUIRED"
Write-Host "  Map ID:       $MAP_ID"
Write-Host "  Module count: $moduleCount"
Write-Host "  BOM:          false"
Write-Host "  Non-ASCII:    false"
Write-Host ""
Write-Host "Launch PZ, host PZMF_B42_MAP9F_NO_MULDRAUGH_001, spawn at 10650,8250."
Write-Host "Confirm biome swatches visible at pixel rows y=5..30 (world y=8205..8230)."
Write-Host "Confirm road crossing visible at world y=8248..8255."
Write-Host "Confirm highway visible at world x=10710..10717."
