#Requires -Version 5.1
<#
.SYNOPSIS
    MAP-6Q: Compares the MAP-6L/MAP-6M candidate LOTH lotheader against
    reference Build 42 LOTH files copied under .local/.

    All inputs and output must be under .local/.
    Does NOT read PZ install folders. Does NOT write outside .local/.
    Does NOT modify any files.

    Writes:
      <Output>/build42-lotheader-candidate-comparison.json
      <Output>/build42-lotheader-candidate-comparison.md

.PARAMETER CandidateLotheader
    Path under .local/ to the candidate 0_0.lotheader file generated by MAP-6L.

.PARAMETER ReferenceRoot
    Path under .local/ containing reference Build 42 *.lotheader files.

.PARAMETER Output
    Path under .local/ for comparison report output.

.PARAMETER MaxReferenceFiles
    Maximum number of reference lotheader files to inspect. Default: 20.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts\compare-build42-lotheader-candidate.ps1 `
        -CandidateLotheader .local\candidate\...\0_0.lotheader `
        -ReferenceRoot .local\reference-build42-map\Dru_map `
        -Output .local\map6q-lotheader-comparison
#>

param(
    [Parameter(Mandatory=$true)][string]$CandidateLotheader,
    [Parameter(Mandatory=$true)][string]$ReferenceRoot,
    [Parameter(Mandatory=$true)][string]$Output,
    [int]$MaxReferenceFiles = 20
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Path guards
# ---------------------------------------------------------------------------

function Assert-LocalPath {
    param([string]$Path, [string]$Label)
    $norm = $Path.Replace('/', '\')
    if ($norm -notmatch '\\\.local(\\|$)') {
        Write-Error "$Label must be under .local/. Got: $Path"
        exit 1
    }
}

Assert-LocalPath $CandidateLotheader '-CandidateLotheader'
Assert-LocalPath $ReferenceRoot      '-ReferenceRoot'
Assert-LocalPath $Output             '-Output'

if (-not (Test-Path -LiteralPath $CandidateLotheader -PathType Leaf)) {
    Write-Error "Candidate lotheader not found: $CandidateLotheader"
    exit 1
}
if (-not (Test-Path -LiteralPath $ReferenceRoot -PathType Container)) {
    Write-Error "ReferenceRoot not found or not a directory: $ReferenceRoot"
    exit 1
}

New-Item -ItemType Directory -Force -Path $Output | Out-Null

# ---------------------------------------------------------------------------
# Helper: read bounded prefix and extract fields
# ---------------------------------------------------------------------------

function Read-LotheaderFields {
    param([string]$Path, [int]$MaxBytes = 128)
    $size  = (Get-Item -LiteralPath $Path).Length
    $limit = [Math]::Min($size, $MaxBytes)
    $bytes = [byte[]]::new($limit)
    $fs    = [System.IO.File]::OpenRead($Path)
    try { [void]$fs.Read($bytes, 0, $limit) } finally { $fs.Dispose() }

    function hex ([byte[]]$b) { ($b | ForEach-Object { $_.ToString('x2') }) -join '' }
    function u32 ([byte[]]$b, [int]$offset) {
        if ($offset + 3 -ge $b.Length) { return $null }
        [BitConverter]::ToUInt32($b, $offset)
    }
    function words64 ([byte[]]$b) {
        $out = [System.Collections.Generic.List[object]]::new()
        for ($i = 0; $i -lt 64; $i += 4) {
            if ($i + 3 -lt $b.Length) {
                $out.Add([BitConverter]::ToUInt32($b, $i))
            } else {
                $out.Add($null)
            }
        }
        [object[]]$out
    }

    $magic16 = if ($limit -ge 16) { hex $bytes[0..15] } else { hex $bytes[0..($limit-1)] }
    $magic64 = if ($limit -ge 64) { hex $bytes[0..63] } else { hex $bytes[0..($limit-1)] }
    $magic128 = if ($limit -ge 128) { hex $bytes[0..127] } else { hex $bytes[0..($limit-1)] }
    $magicAscii = if ($limit -ge 4) { [System.Text.Encoding]::ASCII.GetString($bytes[0..3]) -replace '[^\x20-\x7E]','?' } else { '????' }
    $versionU32 = u32 $bytes 4
    $field8U32  = u32 $bytes 8

    [PSCustomObject]@{
        path               = $Path
        size_bytes         = $size
        first_16_bytes_hex = $magic16
        first_64_bytes_hex = $magic64
        first_128_bytes_hex = $magic128
        magic_ascii        = $magicAscii
        version_u32le      = $versionU32
        field8_u32le       = $field8U32
        u32le_words_first_64 = [object[]](words64 $bytes)
    }
}

# ---------------------------------------------------------------------------
# Read candidate
# ---------------------------------------------------------------------------

Write-Output "Reading candidate: $CandidateLotheader"
$candidate = Read-LotheaderFields -Path $CandidateLotheader

# ---------------------------------------------------------------------------
# Read reference files
# ---------------------------------------------------------------------------

$refFiles = @(Get-ChildItem -LiteralPath $ReferenceRoot -Recurse -Filter '*.lotheader' -File -ErrorAction SilentlyContinue |
    Sort-Object Length -Descending |
    Select-Object -First $MaxReferenceFiles)

Write-Output "Reference files found: $($refFiles.Count)"

$references = [System.Collections.Generic.List[object]]::new()
foreach ($f in $refFiles) {
    Write-Output "  Reading: $($f.Name) ($($f.Length) bytes)"
    $r = Read-LotheaderFields -Path $f.FullName
    $references.Add($r) | Out-Null
}

# ---------------------------------------------------------------------------
# Comparison analysis
# ---------------------------------------------------------------------------

$refSizes      = @($references | ForEach-Object { $_.size_bytes })
$minRefSize    = if ($refSizes.Count -gt 0) { ($refSizes | Measure-Object -Minimum).Minimum } else { 0 }
$maxRefSize    = if ($refSizes.Count -gt 0) { ($refSizes | Measure-Object -Maximum).Maximum } else { 0 }
$candSmaller   = $refSizes.Count -gt 0 -and (@($refSizes | Where-Object { $_ -le $candidate.size_bytes })).Count -eq 0

$refMagics     = @($references | ForEach-Object { $_.magic_ascii } | Group-Object | Select-Object Name, Count)
$refVersions   = @($references | ForEach-Object { $_.version_u32le } | Group-Object | Select-Object Name, Count)
$refField8s    = @($references | ForEach-Object { $_.field8_u32le }  | Group-Object | Select-Object Name, Count)

# Stable reference word summary: for each word position 0..15, record unique values
$stableWords   = [System.Collections.Generic.List[object]]::new()
for ($wi = 0; $wi -lt 16; $wi++) {
    $vals = @($references | ForEach-Object {
        if ($wi -lt $_.u32le_words_first_64.Count) { $_.u32le_words_first_64[$wi] } else { $null }
    } | Where-Object { $null -ne $_ } | Select-Object -Unique)
    $stableWords.Add([PSCustomObject]@{ word_index = $wi; unique_values = [object[]]$vals }) | Out-Null
}

# ---------------------------------------------------------------------------
# Build report
# ---------------------------------------------------------------------------

$report = [ordered]@{
    schema                           = 'pzmapforge.build42-lotheader-comparison.v0.1'
    candidate_lotheader              = $CandidateLotheader
    reference_root                   = $ReferenceRoot
    reference_count                  = $references.Count
    candidate_size_bytes             = $candidate.size_bytes
    min_reference_size_bytes         = $minRefSize
    max_reference_size_bytes         = $maxRefSize
    candidate_smaller_than_all_references = $candSmaller
    candidate_magic                  = $candidate.magic_ascii
    candidate_version                = $candidate.version_u32le
    candidate_field8                 = $candidate.field8_u32le
    candidate_first_16_bytes_hex     = $candidate.first_16_bytes_hex
    candidate_first_64_bytes_hex     = $candidate.first_64_bytes_hex
    candidate_u32le_words_first_64   = $candidate.u32le_words_first_64
    reference_magic_counts           = ($refMagics | ForEach-Object { [ordered]@{ magic = $_.Name; count = $_.Count } })
    reference_version_counts         = ($refVersions | ForEach-Object { [ordered]@{ version = $_.Name; count = $_.Count } })
    reference_field8_counts          = ($refField8s | ForEach-Object { [ordered]@{ field8 = $_.Name; count = $_.Count } })
    reference_stable_word_summary    = [object[]]$stableWords.ToArray()
    reference_records                = [object[]]($references | ForEach-Object {
        [ordered]@{
            file              = [System.IO.Path]::GetFileName($_.path)
            size_bytes        = $_.size_bytes
            magic_ascii       = $_.magic_ascii
            version_u32le     = $_.version_u32le
            field8_u32le      = $_.field8_u32le
            first_16_bytes_hex = $_.first_16_bytes_hex
        }
    })
    status_labels                    = [string[]]@(
        'BUILD42_LOTHEADER_CANDIDATE_COMPARISON_CREATED',
        'CURRENT_CANDIDATE_LOTHEADER_EOF',
        'CANDIDATE_LOTHEADER_TOO_SHORT_OR_INCOMPLETE',
        'WRITER_DIAGNOSTIC_ONLY',
        'WRITER_NOT_CHANGED',
        'LOAD_TEST_NOT_PERFORMED',
        'PLAYABLE_EXPORT_CLAIM_ALLOWED=false'
    )
}

$jsonPath = Join-Path $Output 'build42-lotheader-candidate-comparison.json'
$mdPath   = Join-Path $Output 'build42-lotheader-candidate-comparison.md'

$report | ConvertTo-Json -Depth 6 | Set-Content -Path $jsonPath -Encoding UTF8
Write-Output "Comparison JSON: $jsonPath"

# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------

$fence = '```'

$refTableRows = ($references | ForEach-Object {
    "| $([System.IO.Path]::GetFileName($_.path)) | $($_.size_bytes) | $($_.magic_ascii) | $($_.version_u32le) | $($_.field8_u32le) |"
}) -join "`n"

$md = @"
# MAP-6Q Build 42 Lotheader Candidate Comparison

${fence}text
BUILD42_LOTHEADER_CANDIDATE_COMPARISON_CREATED
CURRENT_CANDIDATE_LOTHEADER_EOF
CANDIDATE_LOTHEADER_TOO_SHORT_OR_INCOMPLETE
WRITER_DIAGNOSTIC_ONLY
WRITER_NOT_CHANGED
LOAD_TEST_NOT_PERFORMED
PLAYABLE_EXPORT_CLAIM_ALLOWED=false
${fence}

## Candidate

| Field | Value |
|---|---|
| Path | $CandidateLotheader |
| Size | $($candidate.size_bytes) bytes |
| Magic | $($candidate.magic_ascii) |
| Version (u32le) | $($candidate.version_u32le) |
| Field8 (u32le) | $($candidate.field8_u32le) |
| First 16 bytes | $($candidate.first_16_bytes_hex) |

## Reference Summary

| Field | Value |
|---|---|
| Reference count | $($references.Count) |
| Min reference size | $minRefSize bytes |
| Max reference size | $maxRefSize bytes |
| Candidate smaller than all refs | $candSmaller |

## Reference Records

| File | Size | Magic | Version | Field8 |
|---|---|---|---|---|
$refTableRows

## Candidate u32le words (first 64 bytes)

$($candidate.u32le_words_first_64 -join ', ')

## Non-claims

- WRITER_NOT_CHANGED: comparison is diagnostic only.
- LOAD_TEST_NOT_PERFORMED: no PZ session was run to produce this report.
- PLAYABLE_EXPORT_CLAIM_ALLOWED=false: binding.
"@

Set-Content -Path $mdPath -Value $md -Encoding ASCII
Write-Output "Comparison MD:   $mdPath"
Write-Output ""
Write-Output "candidate_size_bytes:                    $($candidate.size_bytes)"
Write-Output "min_reference_size_bytes:                $minRefSize"
Write-Output "candidate_smaller_than_all_references:   $candSmaller"
Write-Output "candidate_magic:                         $($candidate.magic_ascii)"
Write-Output "BUILD42_LOTHEADER_CANDIDATE_COMPARISON_CREATED"
Write-Output "WRITER_NOT_CHANGED"
Write-Output "LOAD_TEST_NOT_PERFORMED"
Write-Output "PLAYABLE_EXPORT_CLAIM_ALLOWED=false"
Write-Output "Done."
