#Requires -Version 5.1
<#
.SYNOPSIS
    MAP-8L: Generates a substantial PZMapForge-owned worldmap.xml for the
    PZMapForge parent map folder.

    Source basis: MAP-8K comparator found candidate worldmap.xml skeletal
    (52 bytes, 2 lines) vs Project Russia reference substantial (888KB,
    30959 lines). MAP-8L tests whether a substantial worldmap.xml unblocks
    IsoMetaGrid parent folder mount.

    Generated worldmap.xml describes 1 cell at worldX=35 worldY=27.
    Derived from known PZMapForge cell coordinates only.
    No Project Russia content is used. No binary contents read.
    All output under .local/ only.

.PARAMETER Output
    Required. Output path (must be under .local/).
#>

param(
    [Parameter(Mandatory=$true)][string]$Output
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Assert-LocalPath {
    param([string]$Path, [string]$Label)
    $norm = $Path.Replace('/', '\')
    if ($norm -notmatch '\\\.local(\\|$)') {
        Write-Error "$Label must be under .local/. Got: $Path"
        exit 1
    }
}

Assert-LocalPath $Output '-Output'

New-Item -ItemType Directory -Force -Path $Output | Out-Null

Write-Output "MAP-8L: Worldmap XML Substantial Candidate"
Write-Output "Output: $Output"
Write-Output ""

# ---------------------------------------------------------------------------
# Generate substantial worldmap.xml
# Cell at worldX=35, worldY=27.
# Tile origin:  35*300=10500, 27*300=8100
# Tile extent:  10500+299=10799, 8100+299=8399
# Spawn:        posX=246, posY=188 -> 10500+246=10746, 8100+188=8288
# All content is PZMapForge-owned; no Project Russia data used.
# ---------------------------------------------------------------------------

$worldmapXmlContent = @'
<?xml version="1.0" encoding="ASCII" standalone="yes"?>
<worldmap generator="PZMapForge-map8l" cellwidth="300" cellheight="300">
  <!--
    PZMapForge parent map folder worldmap descriptor.
    Describes single cell at worldX=35 worldY=27.
    Generated by prepare-build42-map8l-worldmap-xml-candidate.ps1.
    Source: MAP-8K comparator result.
    Basis:
      MAP8K candidate worldmap.xml was skeletal (52 bytes 2 lines).
      MAP8K reference worldmap.xml was substantial (888333 bytes 30959 lines).
      MAP8K reference_worldmap_xml_bin_present=true candidate=false.
    Hypothesis:
      Substantial worldmap.xml may be required for IsoMetaGrid parent mount.
    Claim: NOT_A_PLAYABLE_PZ_EXPORT.
    Binary writer gate: CLOSED.
    No Project Russia content copied.
    PZMapForge-owned file. Coordinates derived from known cell data only.
  -->
  <metadata>
    <mapid>PZMapForge</mapid>
    <title>PZMapForge</title>
    <cell_count>1</cell_count>
    <layout>common_media_maps_parent_child</layout>
    <parent_map_id>PZMapForge</parent_map_id>
    <child_map_id>pzmapforge_build42_candidate_v4_001</child_map_id>
    <generator>PZMapForge-map8l-worldmap-xml-candidate</generator>
    <branch>parent_metadata_or_binary_cell_mount_contract</branch>
    <playable_claim>false</playable_claim>
    <binary_writer_gate>CLOSED</binary_writer_gate>
    <no_project_russia_content>true</no_project_russia_content>
  </metadata>
  <cell worldX="35" worldY="27">
    <origin tileX="10500" tileY="8100"/>
    <extent tileX="10799" tileY="8399"/>
    <spawn posX="246" posY="188" posZ="0"/>
    <coordinate_proof>
      <x worldX="35" factor="300" posX="246" result="10746"/>
      <y worldY="27" factor="300" posY="188" result="8288"/>
    </coordinate_proof>
    <lotheader>35_27.lotheader</lotheader>
    <lotpack>world_35_27.lotpack</lotpack>
    <chunkdata>chunkdata_35_27.bin</chunkdata>
  </cell>
</worldmap>
'@

$worldmapXmlPath = Join-Path $Output 'worldmap.xml'
Set-Content -Path $worldmapXmlPath -Value $worldmapXmlContent -Encoding ASCII
$xmlSizeBytes = (Get-Item -LiteralPath $worldmapXmlPath).Length
$xmlLineCount = @(Get-Content -LiteralPath $worldmapXmlPath).Count
$xmlSubstantial = $xmlSizeBytes -ge 500
Write-Output "Wrote: worldmap.xml ($xmlSizeBytes bytes, $xmlLineCount lines, substantial=$xmlSubstantial)"

# ---------------------------------------------------------------------------
# Preflight JSON
# ---------------------------------------------------------------------------

$preflight = [ordered]@{
    schema                              = 'pzmapforge.map8l-preflight.v0.1'
    parent_map_id                       = 'PZMapForge'
    child_map_id                        = 'pzmapforge_build42_candidate_v4_001'
    hypothesis                          = 'worldmap_xml_substantial_may_unblock_iso_meta_grid_mount'
    source_basis                        = 'MAP8K_worldmap_xml_skeletal_discriminator'
    map8k_candidate_worldmap_xml_was    = 'skeletal_52_bytes_2_lines'
    map8k_reference_worldmap_xml_was    = 'substantial_888333_bytes_30959_lines'
    worldmap_xml_substantial            = $xmlSubstantial
    worldmap_xml_size_bytes             = [int]$xmlSizeBytes
    worldmap_xml_line_count             = $xmlLineCount
    worldmap_xml_bin_still_absent       = $true
    cell_worldX                         = 35
    cell_worldY                         = 27
    spawn_posX                          = 246
    spawn_posY                          = 188
    coordinate_proof                    = '35*300+246=10746 27*300+188=8288'
    binary_contents_read                = $false
    no_project_russia_content_used      = $true
    playable_claim_allowed              = $false
    binary_writer_gate_closed           = $true
    next_if_fails                       = 'worldmap_xml_bin_binary_format_investigation'
}

$preflightJsonPath = Join-Path $Output 'map8l-preflight.json'
$preflight | ConvertTo-Json -Depth 3 | Set-Content -Path $preflightJsonPath -Encoding ASCII
Write-Output "Wrote: map8l-preflight.json"

# ---------------------------------------------------------------------------
# Preflight MD
# ---------------------------------------------------------------------------

$preflightMdPath = Join-Path $Output 'map8l-preflight.md'
Set-Content -Path $preflightMdPath -Value @"
# MAP-8L Preflight

``````text
MAP8L_WORLDMAP_XML_SUBSTANTIAL_CANDIDATE_STAGED
BINARY_WRITER_GATE_STILL_CLOSED
PUBLIC_PLAYABLE_CLAIM_ALLOWED=false
``````

``````text
hypothesis:                          worldmap_xml_substantial_may_unblock_iso_meta_grid_mount
source_basis:                        MAP8K_worldmap_xml_skeletal_discriminator
map8k_candidate_worldmap_xml_was:    skeletal_52_bytes_2_lines
map8k_reference_worldmap_xml_was:    substantial_888333_bytes_30959_lines
worldmap_xml_substantial:            $($xmlSubstantial.ToString().ToLower())
worldmap_xml_size_bytes:             $xmlSizeBytes
worldmap_xml_line_count:             $xmlLineCount
worldmap_xml_bin_still_absent:       true
binary_contents_read:                false
no_project_russia_content_used:      true
playable_claim_allowed:              false
binary_writer_gate_closed:           true
next_if_fails:                       worldmap_xml_bin_binary_format_investigation
``````
"@ -Encoding ASCII
Write-Output "Wrote: map8l-preflight.md"

# ---------------------------------------------------------------------------
# Packet doc
# ---------------------------------------------------------------------------

$packetPath = Join-Path $Output 'MAP_8L_WORLDMAP_XML_SUBSTANTIAL_CANDIDATE_PACKET.md'
Set-Content -Path $packetPath -Value @"
# MAP-8L: Worldmap XML Substantial Candidate Packet

``````text
MAP8L_WORLDMAP_XML_SUBSTANTIAL_CANDIDATE_STAGED
BINARY_WRITER_GATE_STILL_CLOSED
PUBLIC_PLAYABLE_CLAIM_ALLOWED=false
NO_THIRD_PARTY_FILES_COPIED
NO_BINARY_CONTENTS_READ
``````

## Artifact

worldmap.xml: $xmlSizeBytes bytes / $xmlLineCount lines / substantial=$($xmlSubstantial.ToString().ToLower())

## Deployment (operator only)

Copy worldmap.xml to Workshop source PZMapForge parent folder.
Re-upload item 3740642200 to Workshop.
Test with:
  Map=pzmapforge_build42_candidate_v4_001;PZMapForge;Muldraugh, KY

## Success criteria

SUCCESS: IsoMetaGrid lists PZMapForge parent folder.
PARTIAL: Different WorldMapDataAssetManager error (new parse error = progress).
FAILURE: IsoMetaGrid still empty -> next = worldmap_xml_bin_binary_format_investigation.

## Packet files

MAP_8L_WORLDMAP_XML_SUBSTANTIAL_CANDIDATE_PACKET.md  (this file)
worldmap.xml
map8l-preflight.json
map8l-preflight.md
"@ -Encoding ASCII
Write-Output "Wrote: MAP_8L_WORLDMAP_XML_SUBSTANTIAL_CANDIDATE_PACKET.md"

Write-Output ""
Write-Output "MAP-8L candidate complete."
Write-Output "worldmap_xml_substantial: $xmlSubstantial"
Write-Output "worldmap_xml_size_bytes:  $xmlSizeBytes"
Write-Output "binary_contents_read:     false"
Write-Output "no_project_russia_content_used: true"
Write-Output "PUBLIC_PLAYABLE_CLAIM_ALLOWED=false"
Write-Output "Done."
