#Requires -Version 5.1
<#
.SYNOPSIS
    Writes the MAP-9C IsoMetaGrid registration packet under .local/ only.
    Produces: map9c-isometagrid-registration-packet.json,
              map9c-isometagrid-registration-packet.md,
              MAP_9C_ISOMETAGRID_REGISTRATION_PACKET.md,
              MAP_9C_HUMAN_RUNTIME_STEPS.md,
              variants/<variant-id>/variant-manifest.json (one per layout hypothesis).
    Does not run Project Zomboid. Does not write to Steam, Workshop, or PZ folders.
    Does not copy third-party files. Does not claim playable export.
    Exits 0 on success, exits 1 on error.
.PARAMETER Output
    Output directory. Must be under .local/ in the repo.
#>

param(
    [string]$Output = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot  = Split-Path -Parent $scriptDir

if (-not $Output) {
    $Output = Join-Path $repoRoot '.local\map9c-isometagrid-registration-packet'
}

# .local/ guard
$localDir  = Join-Path $repoRoot '.local'
$absOutput = [System.IO.Path]::GetFullPath($Output)
$absLocal  = [System.IO.Path]::GetFullPath($localDir)
if (-not $absOutput.StartsWith($absLocal)) {
    Write-Error "prepare-build42-map9c-isometagrid-registration-packet: output must be under .local/ in the repo. Refused: $Output"
    exit 1
}

$forbidden = @('media\maps','media/maps','Steam','workshop','ProjectZomboid','C:\Program Files','D:\Program Files')
foreach ($seg in $forbidden) {
    if ($absOutput -like "*$seg*") {
        Write-Error "prepare-build42-map9c-isometagrid-registration-packet: forbidden path segment '$seg' in output: $Output"
        exit 1
    }
}

New-Item -ItemType Directory -Force -Path $Output | Out-Null
$variantsDir = Join-Path $Output 'variants'
New-Item -ItemType Directory -Force -Path $variantsDir | Out-Null

$generatedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')

# Variant definitions
$variants = @(
    [ordered]@{
        variant_id          = 'variant-A'
        hypothesis          = 'H1-H2'
        folder_layout       = 'common/media/maps/PZMapForge'
        map_folder_name     = 'PZMapForge'
        description         = 'Current known layout — common/media/maps/PZMapForge. Map= token PZMapForge matches folder name.'
        rationale           = 'This is the layout generated by MAP-7L. Tests whether this layout is sufficient for IsoMetaGrid.'
        status              = 'probe_pending_human_runtime_test'
        human_runtime_tested = $false
        isometagrid_result  = 'unknown'
        playable_claim_allowed = $false
    },
    [ordered]@{
        variant_id          = 'variant-B'
        hypothesis          = 'H2'
        folder_layout       = 'common/media/maps/pzmapforge_build42_candidate_v4_001'
        map_folder_name     = 'pzmapforge_build42_candidate_v4_001'
        description         = 'Child map-id layout — folder name matches first Map= token value.'
        rationale           = 'Tests whether IsoMetaGrid requires the folder name to exactly match the first Map= entry.'
        status              = 'probe_pending_human_runtime_test'
        human_runtime_tested = $false
        isometagrid_result  = 'unknown'
        playable_claim_allowed = $false
    },
    [ordered]@{
        variant_id          = 'variant-C'
        hypothesis          = 'H4'
        folder_layout       = '42/media/maps/PZMapForge'
        map_folder_name     = 'PZMapForge'
        description         = 'Build 42 versioned layout — 42/media/maps/PZMapForge.'
        rationale           = 'Tests whether Build 42 scans from the 42/ versioned subtree instead of common/.'
        status              = 'probe_pending_human_runtime_test'
        human_runtime_tested = $false
        isometagrid_result  = 'unknown'
        playable_claim_allowed = $false
    },
    [ordered]@{
        variant_id          = 'variant-D'
        hypothesis          = 'H4-H2'
        folder_layout       = '42/media/maps/pzmapforge_build42_candidate_v4_001'
        map_folder_name     = 'pzmapforge_build42_candidate_v4_001'
        description         = 'Build 42 versioned + child map-id layout.'
        rationale           = 'Tests combination of versioned 42/ subtree and child map-id folder name.'
        status              = 'probe_pending_human_runtime_test'
        human_runtime_tested = $false
        isometagrid_result  = 'unknown'
        playable_claim_allowed = $false
    },
    [ordered]@{
        variant_id          = 'variant-E'
        hypothesis          = 'H1-legacy'
        folder_layout       = 'media/maps/PZMapForge'
        map_folder_name     = 'PZMapForge'
        description         = 'Legacy root layout — media/maps/PZMapForge (no common/ or 42/ prefix).'
        rationale           = 'Tests whether IsoMetaGrid still reads from legacy root media/maps/ in Build 42.'
        status              = 'probe_pending_human_runtime_test'
        human_runtime_tested = $false
        isometagrid_result  = 'unknown'
        playable_claim_allowed = $false
    }
)

# Write variant manifests
foreach ($v in $variants) {
    $vDir = Join-Path $variantsDir $v.variant_id
    New-Item -ItemType Directory -Force -Path $vDir | Out-Null
    $v | ConvertTo-Json -Depth 5 | Set-Content -Encoding UTF8 -Path (Join-Path $vDir 'variant-manifest.json')
}

$packet = [ordered]@{
    schema                                     = 'pzmapforge.map9c-isometagrid-registration-packet.v0.1'
    generated_at_utc                           = $generatedAt
    map9b_debug_runtime_evidence_recorded      = $true
    mod_load_confirmed                         = $true
    workshop_runtime_cache_confirmed           = $true
    spawn_metadata_works                       = $true
    isometagrid_map_folder_list_empty          = $true
    map_folder_registration_unproven           = $true
    playable_terrain_mount_proven              = $false
    canary_writer_available                    = $false
    canary_writer_blocked                      = $true
    current_server_map_line                    = 'Map=pzmapforge_build42_candidate_v4_001;PZMapForge;Muldraugh, KY'
    muldraugh_bootstrap_required               = $true
    no_muldraugh_strategy_rejected             = $true
    registration_probe_goal                    = 'make_PZMapForge_appear_in_IsoMetaGrid_map_folder_list'
    success_signal                             = 'PZMapForge_or_candidate_folder_appears_in_IsoMetaGrid_map_folder_list'
    failure_signal                             = 'IsoMetaGrid_map_folder_list_empty_or_only_vanilla'
    human_manual_runtime_test_required         = $true
    test_one_variant_at_a_time                 = $true
    stale_b41_server_console_ignored           = $true
    debug_build_required                       = $true
    fresh_world_required                       = $true
    layout_variants_defined                    = $variants.Count
    layout_variants                            = @($variants | ForEach-Object { $_.variant_id })
    layout_variant_folder_paths                = @($variants | ForEach-Object { $_.folder_layout })
    playable_claim_allowed                     = $false
    claude_ran_pz                              = $false
    claude_wrote_steam                         = $false
    claude_uploaded_workshop                   = $false
    steam_write_performed                      = $false
    workshop_upload_performed                  = $false
    pz_run_performed                           = $false
    third_party_files_copied                   = $false
    local_only                                 = $true
    recommended_next_branch                    = 'map9c_isometagrid_registration_probe_human_runtime_test_pending'
}

$jsonPath    = Join-Path $Output 'map9c-isometagrid-registration-packet.json'
$mdPath      = Join-Path $Output 'map9c-isometagrid-registration-packet.md'
$overlayDoc  = Join-Path $Output 'MAP_9C_ISOMETAGRID_REGISTRATION_PACKET.md'
$humanSteps  = Join-Path $Output 'MAP_9C_HUMAN_RUNTIME_STEPS.md'

$packet | ConvertTo-Json -Depth 10 | Set-Content -Encoding UTF8 -Path $jsonPath
Write-Output "MAP-9C packet JSON: $jsonPath"

$md = @"
# MAP-9C IsoMetaGrid Registration Packet

Generated: $generatedAt

## Status

- map9b_debug_runtime_evidence_recorded: $($packet.map9b_debug_runtime_evidence_recorded)
- isometagrid_map_folder_list_empty: $($packet.isometagrid_map_folder_list_empty)
- map_folder_registration_unproven: $($packet.map_folder_registration_unproven)
- playable_terrain_mount_proven: $($packet.playable_terrain_mount_proven)
- canary_writer_available: $($packet.canary_writer_available)
- canary_writer_blocked: $($packet.canary_writer_blocked)

## Goal

$($packet.registration_probe_goal)

## Success signal

$($packet.success_signal)

## Failure signal

$($packet.failure_signal)

## Variants ($($variants.Count))

$($variants | ForEach-Object { "- $($_.variant_id): $($_.folder_layout)" } | Out-String)

## Safety

- claude_ran_pz: $($packet.claude_ran_pz)
- claude_wrote_steam: $($packet.claude_wrote_steam)
- third_party_files_copied: $($packet.third_party_files_copied)
- playable_claim_allowed: $($packet.playable_claim_allowed)
"@

$md | Set-Content -Encoding UTF8 -Path $mdPath
Write-Output "MAP-9C packet MD:   $mdPath"

$overlayContent = @"
# MAP-9C IsoMetaGrid Registration Packet Overlay

Generated: $generatedAt

## Classification

``````text
MAP9C_ISOMETAGRID_MAP_FOLDER_REGISTRATION_RESEARCH_PACKET_DEFINED
MAP9B_DEBUG_RUNTIME_BLOCKER_CARRIED_FORWARD=true
ISOMETAGRID_MAP_FOLDER_LIST_EMPTY=true
MOD_LOAD_CONFIRMED=true
SPAWN_METADATA_WORKS=true
MAP_FOLDER_REGISTRATION_UNPROVEN=true
PLAYABLE_TERRAIN_MOUNT_PROVEN=false
CANARY_WRITER_AVAILABLE=false
CANARY_WRITER_BLOCKED=true
MULDRAUGH_BOOTSTRAP_REQUIRED=true
NO_MULDRAUGH_STRATEGY_REJECTED=true
HUMAN_MANUAL_RUNTIME_TEST_REQUIRED=true
TEST_ONE_VARIANT_AT_A_TIME=true
STALE_B41_SERVER_CONSOLE_IGNORED=true
CLAUDE_RAN_PZ=false
CLAUDE_WROTE_STEAM=false
CLAUDE_UPLOADED_WORKSHOP=false
THIRD_PARTY_FILES_COPIED=false
LOCAL_ONLY=true
PLAYABLE_CLAIM_ALLOWED=false
``````

## Layout variants

$($variants | ForEach-Object { "- $($_.variant_id): ``$($_.folder_layout)``" } | Out-String)

## Recommended next branch

$($packet.recommended_next_branch)
"@

$overlayContent | Set-Content -Encoding UTF8 -Path $overlayDoc
Write-Output "MAP-9C overlay doc: $overlayDoc"

$humanStepsContent = @"
# MAP-9C Human Runtime Test Steps

HUMAN-ONLY. Do not automate.
Claude does not run PZ. Claude does not write to Steam/Workshop.

## Current Map line (do not change)

``````
Map=pzmapforge_build42_candidate_v4_001;PZMapForge;Muldraugh, KY
``````

Muldraugh must remain as the last entry. Do not remove it.

## Test procedure (one variant per run)

1. Close Project Zomboid / server completely.
2. Choose one variant from the list below.
3. Manually restructure the Workshop item at:
   ``D:\Program Files (x86)\Steam\steamapps\common\ProjectZomboid\steamapps\workshop\content\108600\3740642200``
   so that the map folder matches the chosen variant's folder_layout.
4. Keep all existing binary files (.lotheader, .lotpack, chunkdata_*.bin) in the new folder.
5. Keep the Map line unchanged.
6. Use a fresh/parked server world.
7. Launch PZ with -debug flag.
8. Join a coop session or start the server.
9. Capture console.txt and coop-console.txt.
10. Search for:

   ``````
   Looking in these map folders:
   PZMapForge
   pzmapforge_build42_candidate_v4_001
   lotheader
   lotpack
   ``````

11. Even if PZMapForge appears in IsoMetaGrid: do NOT claim playable terrain.

## Variants to test (in order)

$($variants | ForEach-Object {
"### $($_.variant_id): $($_.folder_layout)

Hypothesis: $($_.hypothesis)
Description: $($_.description)
Rationale: $($_.rationale)
Status: $($_.status)

"} | Out-String)

## After each test

Record the IsoMetaGrid map folder list from the debug log.
Report which variant was tested and what appeared in the list.
Do NOT test more than one variant per run.
Do NOT claim playable from registration alone.
"@

$humanStepsContent | Set-Content -Encoding UTF8 -Path $humanSteps
Write-Output "MAP-9C human steps: $humanSteps"

Write-Output "outcome: MAP9C_ISOMETAGRID_MAP_FOLDER_REGISTRATION_RESEARCH_PACKET_DEFINED"
Write-Output "MAP9C: isometagrid registration packet complete."
